In [1]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import joblib

In [2]:
# Load the test set
X_test = pd.read_csv('X_test.csv')
y_test = pd.read_csv('y_test.csv')

In [3]:
X_test.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,2,70.95,137.95,1,0,1,0,1,0,...,0,1,0,0,0,1,0,0,1,0
1,1,5,79.90,343.95,0,1,0,1,1,0,...,0,1,0,0,0,1,1,0,0,0
2,1,67,20.05,1263.05,1,0,0,1,1,0,...,0,0,0,1,0,1,1,0,0,0
3,0,58,106.45,6145.85,1,0,1,0,1,0,...,1,0,1,0,0,1,0,0,1,0
4,0,9,20.15,163.70,0,1,1,0,1,0,...,0,0,1,0,0,1,0,0,0,1

In [4]:
# Load the trained model
clf = joblib.load('model.pkl')

In [5]:
# Preprocess the test set
#X_test = pd.get_dummies(X_test, columns=['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
#                                           'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
#                                           'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
#                                           'PaymentMethod'])

In [6]:
# Make predictions on the test set
y_pred = clf.predict(X_test)

In [7]:
# Evaluate the performance of the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f'Test accuracy: {accuracy:.2f}')
print(f'Test precision: {precision:.2f}')
print(f'Test recall: {recall:.2f}')
print(f'Test F1 score: {f1:.2f}')
print(f'Confusion matrix:\n{cm}')

Test accuracy: 0.78
Test precision: 0.67
Test recall: 0.42
Test F1 score: 0.52
Confusion matrix:
[[929  83]
 [228 167]]